type Message = { role: "You" | "LexClear"; content: string };
export function mountChatPanel(host: HTMLElement, documentText: string): void {
  const history: Array<{ role: "user" | "assistant"; content: string }> = [];
  host.innerHTML = '<details class="mt-6 rounded border border-slate-700 p-4"><summary class="cursor-pointer font-bold">Ask about this document</summary><div id="messages" class="mt-3 space-y-2" aria-live="polite"></div><form id="chat-form" class="mt-3"><p class="mb-2 text-xs text-slate-400">General information only — not legal advice.</p><div class="flex gap-2"><label class="sr-only" for="chat-input">Your question about this document</label><input id="chat-input" class="min-w-0 flex-1 rounded border border-slate-600 bg-slate-950 p-2" required><button class="rounded bg-teal-300 px-3 font-bold text-slate-950">Ask</button></div></form></details>';
  const messages = host.querySelector<HTMLElement>("#messages")!;
  const append = (message: Message) => { const item = document.createElement("p"); item.className = "rounded bg-slate-900 p-3 text-sm"; const label = document.createElement("strong"); label.textContent = message.role + ": "; item.append(label, message.content); messages.append(item); };
  host.querySelector<HTMLFormElement>("#chat-form")!.onsubmit = async (event) => {
    event.preventDefault(); const input = host.querySelector<HTMLInputElement>("#chat-input")!; const question = input.value.trim(); if (!question) return; input.value = ""; append({ role: "You", content: question }); history.push({ role: "user", content: question });
    try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ documentText, question, history }) }); const payload = await response.json() as { data?: string }; const answer = payload.data ?? "Assistant unavailable. Please review the document directly."; append({ role: "LexClear", content: answer }); history.push({ role: "assistant", content: answer }); } catch { append({ role: "LexClear", content: "Assistant unavailable. Please review the document directly." }); }
  };
}