import type { SimplifiedResult } from "../lib/gemini";
import { classifyClauses, type ClauseRisk } from "../lib/riskScoring";

type Glossary = NonNullable<SimplifiedResult["glossary"]>;
const translationCache = new Map<string, SimplifiedResult>();
export function renderRiskBadge(level: ClauseRisk): HTMLSpanElement { const badge = document.createElement("span"); badge.className = "ml-2 rounded px-2 py-1 text-xs font-bold " + (level === "high" ? "bg-rose-500/30 text-rose-100" : level === "medium" ? "bg-amber-400/30 text-amber-50" : "bg-teal-400/20 text-teal-100"); badge.textContent = level + " risk"; return badge; }
export function renderSimplifiedView(container: HTMLElement, data: SimplifiedResult, original = data, activeLanguage = ""): void {
  container.hidden = false; container.replaceChildren();
  const heading = document.createElement("h2"); heading.className = "text-2xl font-bold"; heading.textContent = "In plain language";
  const language = document.createElement("select"); language.className = "float-right rounded border border-slate-600 bg-slate-950 p-2"; language.setAttribute("aria-label", "Output language"); language.innerHTML = '<option value="">English</option><option value="hi">Hindi</option><option value="ta">Tamil</option><option value="te">Telugu</option>';
  const text = document.createElement("p"); text.className = "mt-4 whitespace-pre-wrap text-lg leading-8"; text.textContent = data.simplifiedText;
  const pointsTitle = document.createElement("h3"); pointsTitle.className = "mt-7 text-lg font-bold"; pointsTitle.textContent = "Key points";
  const points = document.createElement("ul"); points.className = "mt-3 space-y-3"; classifyClauses(data).forEach((entry) => { const item = document.createElement("li"); item.textContent = entry.point; item.append(renderRiskBadge(entry.level)); points.append(item); });
  language.value = activeLanguage;
  language.onchange = async () => { const target = language.value; if (!target) { renderSimplifiedView(container, original, original, ""); return; } const cacheKey = target + ":" + original.simplifiedText; const cached = translationCache.get(cacheKey); if (cached) { renderSimplifiedView(container, cached, original, target); return; } language.disabled = true; try { const translated = await translateResult(original, target); translationCache.set(cacheKey, translated); renderSimplifiedView(container, translated, original, target); } finally { language.disabled = false; } };
  container.append(language, heading, text, pointsTitle, points);
  const glossary = data.glossary ?? []; if (glossary.length) { const section = document.createElement("section"); section.innerHTML = '<h3 class="mt-7 text-lg font-bold">Glossary</h3>'; glossary.forEach((item) => { const details = document.createElement("details"); details.className = "mt-2"; const summary = document.createElement("summary"); summary.className = "cursor-pointer underline decoration-teal-300 underline-offset-4"; summary.textContent = item.term; const definition = document.createElement("p"); definition.className = "mt-2 text-slate-300"; definition.textContent = item.definition; details.append(summary, definition); section.append(details); }); container.append(section); }
  if (data.caveats.length) { const caveat = document.createElement("aside"); caveat.className = "mt-7 rounded-lg border border-amber-300 bg-amber-100/15 p-4 text-amber-50"; const title = document.createElement("strong"); title.textContent = "Uncertain or incomplete wording"; const message = document.createElement("p"); message.className = "mt-1"; message.textContent = data.caveats.join(" "); caveat.append(title, message); container.append(caveat); }
}
async function translateText(text: string, target: string): Promise<string> { const response = await fetch("/api/translate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text, target }) }); const payload = await response.json() as { data?: string }; return payload.data ?? text; }
async function translateResult(result: SimplifiedResult, target: string): Promise<SimplifiedResult> { const glossary: Glossary = await Promise.all((result.glossary ?? []).map(async item => ({ term: item.term, definition: await translateText(item.definition, target) }))); return { ...result, simplifiedText: await translateText(result.simplifiedText, target), keyPoints: await Promise.all(result.keyPoints.map(item => translateText(item, target))), caveats: await Promise.all(result.caveats.map(item => translateText(item, target))), glossary }; }