import './style.css';
import { fallbackAnalysis, normalizeDocumentText } from './lib/document';
import type { Analysis, ApiResult } from './lib/types';

const app = document.querySelector<HTMLDivElement>('#app');
if (!app) throw new Error('Missing app root');
const root: HTMLDivElement = app;
let sourceText = '';
let analysis: Analysis | null = null;
const sample = 'SERVICE AGREEMENT. Customer shall pay invoices within 15 days. This agreement automatically renews annually unless either party provides 30 days written notice. Customer agrees to indemnify Acme for claims arising from Customer use. The agreement may be terminated for material breach.';
const esc = (value: string) => value.replace(/[&<>\"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '\"':'&quot;', "'":'&#039;' })[char]!);
const get = <T extends Element>(selector: string): T => { const found = document.querySelector<T>(selector); if (!found) throw new Error('Missing '+selector); return found; };
async function post<T>(url: string, body: unknown): Promise<{data:T;warning?:string}> { const response = await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const payload = await response.json() as ApiResult<T>&{warning?:string}; if (!response.ok || !payload.data) throw new Error(payload.error||'Request failed'); return {data:payload.data,warning:payload.warning}; }
function page(content: string): void { root.innerHTML = '<header class="border-b border-slate-800"><nav class="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><a href="/" class="text-xl font-black text-white">Lex<span class="text-teal-300">Clear</span></a><span class="text-xs text-teal-200">Private by design · no saved files</span></nav></header><main id="main-content" class="mx-auto max-w-6xl px-5 py-10">'+content+'</main><footer class="mx-auto max-w-6xl px-5 pb-10 text-sm text-slate-400">Legal information, not legal advice.</footer>'; }
function home(): void { page('<section class="grid gap-8 lg:grid-cols-2"><div><p class="font-bold uppercase tracking-widest text-teal-300">Legal information, made usable</p><h1 class="mt-3 text-5xl font-black text-white">Understand the fine print.</h1><p class="mt-5 text-lg leading-8 text-slate-300">Gemini simplifies your agreement, Vision reads scanned pages, and Translation makes the result accessible.</p></div><aside class="rounded-2xl border border-slate-700 bg-slate-900 p-6"><b>Private by design</b><p class="mt-2 text-slate-300">Files are processed for this request only and never saved.</p></aside></section><section class="mt-10 rounded-2xl border border-slate-700 bg-slate-900 p-6"><h2 class="text-2xl font-bold">Review a document</h2><label id="drop" for="file" class="mt-5 block cursor-pointer rounded-xl border-2 border-dashed border-slate-600 p-7 text-center transition-colors"><b>Drop a scan here or choose a file</b><br><span class="text-sm text-slate-400">PNG, JPG or WEBP · Google Cloud Vision OCR</span></label><input id="file" class="sr-only" type="file" accept="image/png,image/jpeg,image/webp"><textarea id="text" class="mt-5 min-h-40 w-full rounded-xl border border-slate-600 bg-slate-950 p-4" placeholder="Or paste legal document text…" aria-label="Legal document text"></textarea><div class="mt-4 flex gap-3"><button id="sample" class="rounded-lg border border-slate-500 px-4 py-2">Use sample</button><button id="analyze" class="rounded-lg bg-teal-300 px-4 py-2 font-bold text-slate-950">Simplify document →</button><span id="status" class="self-center text-sm text-slate-400" role="status"></span></div></section>');
const text = get<HTMLTextAreaElement>('#text'); text.value=sourceText; get<HTMLButtonElement>('#sample').onclick=()=>{text.value=sample;sourceText=sample;}; get<HTMLButtonElement>('#analyze').onclick=()=>analyzeText(text.value); const drop=get<HTMLLabelElement>('#drop'); const file=get<HTMLInputElement>('#file'); ['dragenter','dragover'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.add('drop-active');})); ['dragleave','drop'].forEach(name=>drop.addEventListener(name,event=>{event.preventDefault();drop.classList.remove('drop-active');})); drop.addEventListener('drop', event=>useFile(event.dataTransfer?.files[0])); file.onchange=()=>useFile(file.files?.[0]); }
function loading(): void { page('<section class="mx-auto max-w-xl py-20 text-center"><p class="font-bold uppercase tracking-widest text-teal-300">Processing securely</p><h1 class="mt-3 text-3xl font-black">Making the legal language clear</h1><ol class="mt-8 space-y-3 text-left" aria-live="polite"><li class="rounded-lg bg-slate-900 p-4">✓ Preparing document</li><li class="rounded-lg bg-slate-900 p-4">◌ Extracting text with Google Cloud Vision</li><li class="rounded-lg bg-slate-900 p-4">◌ Simplifying and checking clauses with Gemini</li></ol></section>'); }
async function analyzeText(value:string): Promise<void> { sourceText=normalizeDocumentText(value); if(sourceText.length<20){get<HTMLElement>('#status').textContent='Paste at least a short clause to continue.';return;} loading(); try { analysis=(await post<Analysis>('/api/analyze',{title:'Pasted document',text:sourceText})).data; } catch { analysis=fallbackAnalysis('Pasted document',sourceText); } results(); }
async function useFile(item?:File): Promise<void> { if(!item)return; const status=get<HTMLElement>('#status'); if(!['image/png','image/jpeg','image/webp'].includes(item.type)||item.size>4000000){status.textContent='Choose a PNG, JPG, or WEBP under 4 MB.';return;} const url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(item);}); loading(); try { analysis=(await post<Analysis>('/api/analyze',{title:item.name,imageBase64:url.split(',')[1],mimeType:item.type})).data; sourceText=analysis.plainLanguage; } catch { analysis=fallbackAnalysis(item.name,''); } results(); }
function results(): void { if(!analysis){home();return;} const risks=analysis.risks.length?analysis.risks.map(r=>'<li class="rounded-lg border border-slate-700 p-3"><b>'+esc(r.clause)+'</b><p class="mt-1 text-sm text-slate-300">'+esc(r.reason)+'</p></li>').join(''):'<li class="text-teal-100">No common high-attention patterns detected.</li>'; const glossary=analysis.glossary.map(g=>'<details class="border-b border-slate-700 py-3"><summary class="cursor-pointer font-bold">'+esc(g.term)+'</summary><p class="mt-2 text-sm text-slate-300">'+esc(g.meaning)+'</p></details>').join('')||'<p class="text-slate-400">No technical terms detected.</p>'; page('<a id="restart" href="/" class="font-bold text-teal-300">← Review another document</a><section class="mt-6 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><div><p class="font-bold uppercase tracking-widest text-teal-300">'+(analysis.source==='gemini'?'Gemini analysis':'Local fallback review')+'</p><h1 class="mt-3 text-4xl font-black">'+esc(analysis.title)+'</h1><article class="mt-6 rounded-2xl bg-slate-900 p-6"><h2 class="text-xl font-bold">In plain language</h2><p id="plain" class="mt-3 whitespace-pre-wrap leading-7 text-slate-200">'+esc(analysis.plainLanguage)+'</p><select id="language" class="mt-5 rounded-lg border border-slate-600 bg-slate-950 p-2" aria-label="Translate summary"><option value="">Translate summary…</option><option value="hi">Hindi</option><option value="ta">Tamil</option><option value="te">Telugu</option><option value="bn">Bengali</option><option value="mr">Marathi</option></select><span id="translate-status" class="ml-2 text-sm text-slate-400" role="status"></span></article><article class="mt-6 rounded-2xl border border-slate-700 p-6"><h2 class="text-xl font-bold">Ask about this document</h2><div id="chat" class="mt-4 space-y-3" aria-live="polite"></div><form id="ask" class="mt-4 flex gap-2"><input id="question" class="min-w-0 flex-1 rounded-lg border border-slate-600 bg-slate-950 p-2" placeholder="What does the renewal clause mean?" aria-label="Your question" required><button class="rounded-lg bg-teal-300 px-4 font-bold text-slate-950">Ask</button></form></article></div><aside class="space-y-6"><section class="rounded-2xl border border-slate-700 p-6"><h2 class="text-xl font-bold">Things to review</h2><ul class="mt-4 space-y-3">'+risks+'</ul></section><section class="rounded-2xl border border-slate-700 p-6"><h2 class="text-xl font-bold">Glossary</h2>'+glossary+'</section><section class="rounded-2xl border border-slate-700 p-6"><h2 class="text-xl font-bold">Key dates</h2><p class="mt-3 text-slate-300">'+esc(analysis.keyDates.join(' · ')||'No dates detected.')+'</p></section></aside></section>'); get<HTMLAnchorElement>('#restart').onclick=e=>{e.preventDefault();home();}; get<HTMLSelectElement>('#language').onchange=translate; get<HTMLFormElement>('#ask').onsubmit=ask; }
async function translate(): Promise<void> { if(!analysis)return; const target=get<HTMLSelectElement>('#language').value; if(!target)return; const status=get<HTMLElement>('#translate-status');status.textContent='Translating…';try{const result=await post<string>('/api/translate',{text:analysis.plainLanguage,target});get<HTMLElement>('#plain').textContent=result.data;status.textContent=result.warning||'Translated with Google Cloud Translation.';}catch{status.textContent='Translation unavailable; English is shown.';} }
async function ask(event:SubmitEvent): Promise<void> { event.preventDefault();const input=get<HTMLInputElement>('#question');const question=input.value.trim();if(!question)return;input.value='';const log=get<HTMLElement>('#chat');log.innerHTML+='<p class="rounded-lg bg-slate-800 p-3 text-sm"><b>You:</b> '+esc(question)+'</p>';try{const response=await post<string>('/api/ask',{documentText:sourceText,question});log.innerHTML+='<p class="rounded-lg bg-teal-300/10 p-3 text-sm"><b>LexClear:</b> '+esc(response.data)+'</p>';}catch{log.innerHTML+='<p class="rounded-lg bg-rose-400/10 p-3 text-sm">The assistant is unavailable. Please try again.</p>';}}
home();
