import "./style.css";
import { wireUpload } from "./views/upload";
import type { SimplifiedResult } from "./lib/gemini";
import { renderSimplifiedView } from "./views/simplifiedView";
import { mountChatPanel } from "./views/chatPanel";

const app = document.querySelector<HTMLElement>("#app");
if (!app) throw new Error("Missing app");
app.innerHTML = '<main id="main-content" class="mx-auto max-w-4xl p-5 sm:p-8"><h1 class="text-4xl font-black">LexClear</h1><p class="mt-2 text-slate-300">Upload a legal document for a plain-language review.</p><section class="mt-8 rounded-xl border border-slate-700 p-6"><label id="drop-zone" for="document-file" class="block cursor-pointer rounded-lg border-2 border-dashed border-slate-600 p-8 text-center transition hover:border-teal-300">Drop PDF, DOCX, PNG, or JPG here<br><span class="text-sm text-slate-400">Up to 10 MB</span></label><input id="document-file" class="sr-only" type="file" accept="application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,image/png,image/jpeg"><p id="ingestion-status" class="mt-3" role="status" aria-live="polite"></p></section><section id="results" class="mt-8" hidden></section><section id="chat-host"></section><details class="mt-8"><summary class="cursor-pointer text-sm font-bold text-teal-300">Add a second document to compare</summary><div class="mt-3 rounded-xl border border-slate-700 p-5"><label id="compare-drop-zone" for="compare-file" class="block cursor-pointer rounded-lg border-2 border-dashed border-slate-600 p-5 text-center">Drop or choose the second document</label><input id="compare-file" class="sr-only" type="file" accept="application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,image/png,image/jpeg"><p id="compare-status" class="mt-3" role="status" aria-live="polite"></p></div></details><div id="compare-host"></div></main><footer class="mx-auto max-w-4xl px-5 pb-8 text-sm text-slate-400">LexClear explains documents in plain language. It is not a substitute for legal advice.</footer>';
const results = document.querySelector<HTMLElement>("#results")!; const chatHost = document.querySelector<HTMLElement>("#chat-host")!; const compareHost = document.querySelector<HTMLElement>("#compare-host")!;
let firstText = "";
wireUpload(document.querySelector<HTMLElement>("#drop-zone")!, document.querySelector<HTMLInputElement>("#document-file")!, document.querySelector<HTMLElement>("#ingestion-status")!, { onText: async (text) => { firstText = text; const response = await fetch("/api/simplify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: "Uploaded document", text }) }); const payload = await response.json() as { data?: SimplifiedResult; error?: string }; if (!response.ok || !payload.data) throw new Error(payload.error ?? "Simplification failed"); renderSimplifiedView(results, payload.data); mountChatPanel(chatHost, text); } });
wireUpload(document.querySelector<HTMLElement>("#compare-drop-zone")!, document.querySelector<HTMLInputElement>("#compare-file")!, document.querySelector<HTMLElement>("#compare-status")!, { onText: async (secondText) => { if (!firstText) throw new Error("Upload the primary document before adding one to compare."); const view = await import("./views/compareView"); await view.mountCompareView(compareHost, firstText, secondText); } });